# Generated by Django 5.1.1 on 2024-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/', verbose_name='фото'),
        ),
    ]
