# Generated by Django 5.1.1 on 2024-09-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_about_banner_alter_about_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='фото2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='фото1'),
        ),
    ]
